/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_joselagos;

import javax.swing.JOptionPane;

/**
 *
 * @author tonye
 */
public class LoginUsers extends javax.swing.JFrame {

    /**
     * Creates new form LoginUsers
     */
    public LoginUsers() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Alumno = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tp_PasswordAlumnos = new javax.swing.JPasswordField();
        tf_UserAlumnos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jd_Docente = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_UserDocente = new javax.swing.JTextField();
        tp_PasswordDocente = new javax.swing.JPasswordField();
        btn_IngresarDocente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_AccesoAlumno = new javax.swing.JButton();
        btn_AccesoDocente = new javax.swing.JButton();

        jLabel2.setText("Ingrese nombre de usuario:");

        jLabel3.setText("Ingrese contraseña:");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_AlumnoLayout = new javax.swing.GroupLayout(jd_Alumno.getContentPane());
        jd_Alumno.getContentPane().setLayout(jd_AlumnoLayout);
        jd_AlumnoLayout.setHorizontalGroup(
            jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AlumnoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_UserAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_AlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(tp_PasswordAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jd_AlumnoLayout.setVerticalGroup(
            jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AlumnoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_UserAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jd_AlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tp_PasswordAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel4.setText("Ingrese nombre de usuario:");

        jLabel5.setText("Ingrese contraseña");

        btn_IngresarDocente.setText("Ingresar");
        btn_IngresarDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IngresarDocenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_DocenteLayout = new javax.swing.GroupLayout(jd_Docente.getContentPane());
        jd_Docente.getContentPane().setLayout(jd_DocenteLayout);
        jd_DocenteLayout.setHorizontalGroup(
            jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DocenteLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_DocenteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_UserDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_DocenteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_IngresarDocente)
                            .addComponent(tp_PasswordDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jd_DocenteLayout.setVerticalGroup(
            jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_DocenteLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_UserDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_DocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tp_PasswordDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_IngresarDocente)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Usuarios");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Seleccione el tipo de usuario");

        btn_AccesoAlumno.setText("Alumno");
        btn_AccesoAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AccesoAlumnoMouseClicked(evt);
            }
        });
        btn_AccesoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AccesoAlumnoActionPerformed(evt);
            }
        });

        btn_AccesoDocente.setText("Docente");
        btn_AccesoDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AccesoDocenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_AccesoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btn_AccesoDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_AccesoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(btn_AccesoDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AccesoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AccesoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AccesoAlumnoActionPerformed

    private void btn_AccesoAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccesoAlumnoMouseClicked
        AlumnosLogin();

    }//GEN-LAST:event_btn_AccesoAlumnoMouseClicked

    private void btn_AccesoDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AccesoDocenteMouseClicked
        DocentesLogin();
    }//GEN-LAST:event_btn_AccesoDocenteMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String user = tf_UserAlumnos.getText();
        String clave = tp_PasswordAlumnos.getText();
        String usuario = "";
        String password = "";
        int flag = 0;
        Administrador admin = new Administrador("./Alumnos.txt");
        admin.cargarArchivoAlumno();

        for (int i = 0; i < admin.getAlumnos().size(); i++) {
            for (Alumnos alumno : admin.getAlumnos()) {
                user += admin.getAlumnos().get(i).getUser();
                password += admin.getAlumnos().get(i).getPassword();

                if (user.equals(usuario) && clave.equals(password)) {
                    this.dispose();
                    AlumnosMenu menu = new AlumnosMenu();
                    menu.setVisible(true);
                    flag++;
                }
            }
        }
        if(flag == 0){
            JOptionPane.showMessageDialog(jd_Alumno,"El usuario ingresado no existe");
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void btn_IngresarDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresarDocenteMouseClicked
        String user = tf_UserDocente.getText();
        String clave = tp_PasswordDocente.getText();
        String usuario = "";
        String password = "";
        int flag = 0;
        Administrador admin = new Administrador("./Docente.txt");
        admin.cargarArchivoAlumno();

        for (int i = 0; i < admin.getDocente().size(); i++) {
            for (Docentes docente : admin.getDocente()) {
                user += admin.getDocente().get(i).getUser();
                password += admin.getDocente().get(i).getPassword();

                if (user.equals(usuario) && clave.equals(password)) {
                    this.dispose();
                    DocentesMenu menu = new DocentesMenu();
                    menu.setVisible(true);
                    flag++;
                }
            }
        }
        if(flag == 0){
            JOptionPane.showMessageDialog(jd_Alumno,"El usuario ingresado no existe");
        }
    }//GEN-LAST:event_btn_IngresarDocenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsers().setVisible(true);
            }
        });
    }

    private void AlumnosLogin() {
        jd_Alumno.setModal(true);//bloquea el fondo
        jd_Alumno.pack();//permite ampliar el tamaño de la ventana
        jd_Alumno.setLocationRelativeTo(null);

        jd_Alumno.setVisible(true);
    }

    private void DocentesLogin() {
        jd_Docente.setModal(true);//bloquea el fondo
        jd_Docente.pack();//permite ampliar el tamaño de la ventana
        jd_Docente.setLocationRelativeTo(null);

        jd_Docente.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AccesoAlumno;
    private javax.swing.JButton btn_AccesoDocente;
    private javax.swing.JButton btn_IngresarDocente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JDialog jd_Alumno;
    private javax.swing.JDialog jd_Docente;
    private javax.swing.JTextField tf_UserAlumnos;
    private javax.swing.JTextField tf_UserDocente;
    private javax.swing.JPasswordField tp_PasswordAlumnos;
    private javax.swing.JPasswordField tp_PasswordDocente;
    // End of variables declaration//GEN-END:variables
}
